---
version: 1

build_arg_defaults:
  #EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ee-minimal-rhel8:latest'
  EE_BASE_IMAGE:  'registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8:latest'

#ansible_config: '../ansible.cfg'

dependencies:
  galaxy: requirements.yml
#  python: Pythonrequiremnts.txt
  system: bindep.txt

additional_build_steps:
  prepend:
    - COPY krb5.conf /etc/krb5.conf
    - RUN pip3 install --upgrade pip
    - RUN pip3 install --upgrade pip setuptools
   # - RUN pip3 install azure==4.0.0 --upgrade
  append:
    - RUN ls -la /etc
#    - COPY cert-chain.crt /etc/pki/ca-trust/source/anchors/cert-chain.crt 
    - RUN update-ca-trust
    - RUN microdnf install crypto-policies-scripts
    - RUN update-crypto-policies --set DEFAULT:AD-SUPPORT
