# Workflow name
name: EE build (reusable)


# Controls when the workflow will run
on:
  # This is a reusable workflow
  workflow_call:
    inputs:
      EE_FOLDER_NAME:
        description: 'name of the folder where the EE is located (will become the name of the EE)'
        default: ''
        required: true
        type: string
      EE_IMAGE_TAG:
        description: 'just one tag for image build'
        default: 'latest'
        required: true
        type: string
      AAP_USER:
        description: 'this is used during the image push to AAP'
        required: false
        type: string
 #     EE_DATE:
 #       description: 'todays date'
 #       default: '' 
 #       required: true
 #       type: string 
      EE_REG:
        description: 'registry url'
        default: '' 
        required: true
        type: string 
    secrets:
      HUB_PASSWORD:
        description: 'needed for registry login'
        required: false
      HUB_USERNAME:
        description: 'needed for registry login'
        required: false
#      AH_TOKEN:
#        description: 'API token for hosted automation hub'
#        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    runs-on: self-hosted
    environment: deploy
    steps:

      - name: Chown user
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      # In this job, all steps begin with a name
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Install python requirements (ansible-builder)
        run: pip install -r requirements.txt

      - name: Log in to automation hub
        id: registry-AAP
        uses: redhat-actions/podman-login@v1
        with:
          registry: hub.aapbmylc6irzyfx6.ansiblecloud.redhat.com
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

#      - name: Log in to registry.redhat.io
#        id: registry-redhat
#        uses: redhat-actions/podman-login@v1
#        with:
#          registry: registry.redhat.io
#          username: ${{ secrets.REDHAT_USERNAME }}
#          password: ${{ secrets.REDHAT_PASSWORD }}
          
#      - name: substitute token for automation hub
#        id: ah-token
#        run: |
#          sed -i "s/my_ah_token/$AH_TOKEN/1" ansible.cfg
#        env:
#          AH_TOKEN: ${{ secrets.AH_TOKEN }}

      - name: Get current date
        id: version
        run: |
          echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
#          echo $GITHUB_STATE \
#          echo env.date

#      - name: Get current date2
#        id: date2
#        run: |
#          NOW=$(date +%Y-%m-%d)
#          echo $NOW
#      - name: Print date2
#        id: date3
#        run: |
#          echo $NOW 
#        echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build image
        id: build-image
        working-directory: ${{ inputs.EE_FOLDER_NAME }}
        run: |
          sudo /usr/local/bin/ansible-builder build \
          --context=../${{ inputs.EE_FOLDER_NAME }} \
          --tag=${{ inputs.EE_REG }}:${{ steps.version.outputs.builddate }}
#          --tag=hub.aapbmylc6irzyfx6.ansiblecloud.redhat.com/vcc_ee:${{ env.builddate}}

      - name: Push image
        id: push-to-AAP
        working-directory: ${{ inputs.EE_FOLDER_NAME }}
        run: |
          sudo podman push \
          hub.aapbmylc6irzyfx6.ansiblecloud.redhat.com/vcc_ee:${{ env.builddate}}
      - name: Print image url
        run: echo "Image pushed to $hub.aapbmylc6irzyfx6.ansiblecloud.redhat.com/vcc_ee:${{ env.builddate}}"

#         env:
#           ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN: ${{ secrets.AH_TOKEN }}
# Above env var doesn't work yet: https://github.com/ansible/ansible-builder/issues/346
           

