# Workflow name
name: VCC EE build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'vcc_ee/**'

  # Schedule workflow run at 00:00 on Sunday
  schedule:
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-deploy-workflow:
    uses:  styxxen21/ee-builds/.github/workflows/deploy.yml@main
    with:
      EE_FOLDER_NAME: 'vcc_ee'
      EE_IMAGE_TAG: 'latest'
      EE_REG: 'hub.aapbmylc6irzyfx6.ansiblecloud.redhat.com/vcc_ee'
#      EE_DATE: '20230124'
#      AAP_USER: 'cr-ansiblehub-ee'
    secrets:
      HUB_USERNAME: ${{ secrets.HUB_USERNAME }}
      HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
